# Generated by Django 5.0.3 on 2024-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('PurchaseDate', models.DateTimeField(auto_now_add=True)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TotalQuantity', models.IntegerField()),
                ('CustomerID', models.IntegerField()),
            ],
        ),
    ]
