# Generated by Django 5.0.3 on 2024-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DeliveryID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeliveryStatus', models.BooleanField()),
                ('DeliveryDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
