# Generated by Django 5.0.3 on 2024-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryStatus',
            field=models.CharField(max_length=20),
        ),
    ]
