# Generated by Django 5.0.3 on 2024-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductID', models.IntegerField()),
                ('TransactionID', models.IntegerField()),
                ('CartID', models.IntegerField()),
                ('PaymentID', models.IntegerField()),
                ('QuantityPerProduct', models.IntegerField()),
                ('DatePurchased', models.DateTimeField(auto_now_add=True)),
                ('DeliveryID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.IntegerField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('PaymentMethod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('PurchaseDate', models.DateTimeField(auto_now_add=True)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TotalQuantity', models.IntegerField()),
                ('CustomerID', models.IntegerField()),
            ],
        ),
    ]
