# Generated by Django 5.0.3 on 2024-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductID', models.IntegerField()),
                ('QuantityPerProduct', models.IntegerField()),
                ('TransactionID', models.IntegerField()),
            ],
        ),
    ]
