# Generated by Django 5.0.3 on 2024-04-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
    ]
